tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "archey"
brew "cabextract"
brew "python@3.9"
brew "cmake"
brew "dark-mode"
brew "darksky-weather"
brew "harfbuzz"
brew "ffmpeg"
brew "fftw"
brew "git"
brew "glances"
brew "htop"
brew "imagemagick"
brew "imgur-screenshot"
brew "instalooter"
brew "ipcalc"
brew "livestreamer"
brew "lsd"
brew "mas"
brew "mosh"
brew "mpd"
brew "mpssh"
brew "taglib"
brew "ncmpcpp"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "nyancat"
brew "pipes-sh"
brew "pwgen"
brew "showkey"
brew "spaceinvaders-go"
brew "speedtest-cli"
brew "streamlink"
brew "tldr"
brew "tmux"
brew "watch"
brew "wget"
brew "whois"
brew "wifi-password"
brew "youtube-dl"
cask "background-music"
cask "powershell"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Microsoft Remote Desktop", id: 1295203466
mas "OneDrive", id: 823766827
mas "Steam Link", id: 1246969117
mas "Telegram", id: 747648890
