require("bee.options")
require("bee.keymaps")
require("bee.plugins")
require("bee.colorscheme")
require("bee.cmp")
require("bee.lsp")
require("bee.feline")
require("bee.neoclip")
-- require "bee.telescope" -- required by neoclip already
require("bee.treesitter")
require("bee.autopairs")
require("bee.gitsigns")
require("bee.comment")
require("bee.nvim-tree")
require("bee.bufferline")
require("bee.toggleterm")
