" if empty(glob('~/.vim/autoload/plug.vim'))                                      "Plug install for Vim
"   silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs                      "Plug install for Vim
"     \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim       "Plug install for Vim
"   autocmd VimEnter * PlugInstall --sync | source $MYVIMRC                       "Plug install for Vim
" endif                                                                           "Plug install for Vim

if empty(glob('~/.vim/autoload/plug.vim'))                                        "Plug install for Neovim 
  silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs      "Plug install for Neovim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim         "Plug install for Neovim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC                         "Plug install for Neovim
endif                                                                             "Plug install for Neovim

" Normal Mode - Set arrow keys to homerow, swap up and down
nmap ; <right>
nmap l <down>
nmap k <up>
nmap j <left>
" Visual Mode - Set arrow keys to homerow, swap up and down
vmap ; <right>
vmap l <down>
vmap k <up>
vmap j <left>

set nu                                                                              "enable line numbers

" Adds support for leaving insert mode with jj
inoremap jj <Esc>

" Plugins
call plug#begin('~/.vim/plugged')
Plug 'deviantfero/wpgtk.vim'                                                        "wpgtk color support
Plug 'scrooloose/nerdtree'                                                          "NerdTree folder browser
Plug 'bling/vim-airline'                                                            "Powerline vim statusbar
Plug 'vim-airline/vim-airline-themes'                                               "Theming support for Airline
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }                   "Adds search functionality
Plug 'junegunn/fzf.vim'                                                             "Adds ag search
" Plug 'edkolev/tmuxline.vim'                                                       "themes tmux to the current Airline theme
call plug#end()

colorscheme wpgtk                                                                   "enables wpgtk color support

let g:airline_theme = 'dark'                                                        "sets the Airline theme
let g:airline_powerline_fonts = 1                                                   "enables powerline for Airline

" hotkey bindings
let mapleader = ","
nnoremap <leader>d :NERDTreeToggle<cr>
nnoremap <leader>a :Ag<cr>
